/**
 * Encounters-only Pokénav for the games without a decompilation (Generation 5 onward): the
 * locations and what lives in them, straight from the Pokédex files (`npm run pokedex`: PokeAPI +
 * PKHeX encounter tables). Wild, static, gift and trade encounters are all there; maps, items, NPCs,
 * shops and trainer teams aren't, because none of the pinned sources has them (docs/atlas-sources.md).
 */
import type { AtlasFile, AtlasLocation, LocationKind } from '../../src/domain/atlasTypes.ts';
import { OUT, readJSON } from './common.ts';
import { resolve } from 'node:path';

/** The parts of pokedex-<book>.json this builder reads (shape: src/domain/pokedex.ts). */
interface PokedexData {
  games: { id: string }[];
  areas: { loc: string; name: string }[];
  methods: string[];
  encounters: Record<string, [number, number, number, ...unknown[]][]>;
}

export interface LiteGame {
  /** Atlas game id (the file is atlas-<id>.json). */
  id: string;
  name: string;
  /** Pokédex file id (gen5, lgpe, …) and the Pokédex game ids whose encounters this file covers. */
  book: string;
  generation: number;
  dexGames: string[];
}

export const LITE_GAMES: LiteGame[] = [
  { id: 'black', name: 'Pokémon Black / White', book: 'gen5', generation: 5, dexGames: ['black', 'white'] },
  { id: 'black2', name: 'Pokémon Black 2 / White 2', book: 'gen5', generation: 5, dexGames: ['black-2', 'white-2'] },
  { id: 'x', name: 'Pokémon X / Y', book: 'gen6', generation: 6, dexGames: ['x', 'y'] },
  { id: 'omegaruby', name: 'Pokémon Omega Ruby / Alpha Sapphire', book: 'gen6', generation: 6, dexGames: ['omega-ruby', 'alpha-sapphire'] },
  { id: 'sun', name: 'Pokémon Sun / Moon', book: 'gen7', generation: 7, dexGames: ['sun', 'moon'] },
  { id: 'ultrasun', name: 'Pokémon Ultra Sun / Ultra Moon', book: 'gen7', generation: 7, dexGames: ['ultra-sun', 'ultra-moon'] },
  { id: 'letsgopikachu', name: 'Pokémon Let’s Go, Pikachu! / Eevee!', book: 'lgpe', generation: 7, dexGames: ['lets-go-pikachu', 'lets-go-eevee'] },
  { id: 'sword', name: 'Pokémon Sword / Shield', book: 'gen8', generation: 8, dexGames: ['sword', 'shield'] },
  { id: 'brilliantdiamond', name: 'Pokémon Brilliant Diamond / Shining Pearl', book: 'bdsp', generation: 8, dexGames: ['brilliant-diamond', 'shining-pearl'] },
  { id: 'legendsarceus', name: 'Pokémon Legends: Arceus', book: 'pla', generation: 8, dexGames: ['legends-arceus'] },
  { id: 'scarlet', name: 'Pokémon Scarlet / Violet', book: 'gen9', generation: 9, dexGames: ['scarlet', 'violet'] },
  { id: 'legendsza', name: 'Pokémon Legends: Z-A', book: 'za', generation: 9, dexGames: ['legends-za'] },
];

/** A best guess from the name alone; the encounter tables don't say what kind of place it is. */
export function kindOf(name: string): LocationKind {
  const n = name.toLowerCase();
  if (/\bsea\b|ocean|\bbay\b|\blake\b|\bsurf/.test(n) && /route|sea/.test(n)) return 'sea-route';
  if (/route|road|\bpath\b|trail|\bwild area\b|\bwild zone\b|\bfield\b/.test(n)) return 'route';
  if (/\bcity\b/.test(n)) return 'city';
  if (/\btown\b|village|\bhamlet\b/.test(n)) return 'town';
  if (/cave|cavern|tunnel|mine|grotto|\bden\b|\bpit\b|\bburrow|lair/.test(n)) return 'cave';
  if (/tower|ruins|temple|castle|\bgate\b|\bvault|\bpalace|\bmansion|\bfactory|\blab|\bplant\b|\bhall\b/.test(n)) return 'dungeon';
  return 'landmark';
}

export function buildEncounters(g: LiteGame): { file: AtlasFile; gaps: string } {
  const pd = readJSON<PokedexData>(resolve(OUT, `pokedex-${g.book}.json`));
  const gameIdx = new Set(g.dexGames.map((id) => pd.games.findIndex((x) => x.id === id)));
  if (gameIdx.has(-1)) throw new Error(`${g.id}: ${g.dexGames.join(', ')} not all in pokedex-${g.book}.json`);
  const locations: Record<string, AtlasLocation> = {};
  const staticLocs = new Set<string>();
  let rows = 0;
  for (const encs of Object.values(pd.encounters))
    for (const [game, area, method] of encs) {
      if (!gameIdx.has(game)) continue;
      rows++;
      const a = pd.areas[area];
      locations[a.loc] ??= {
        id: a.loc, name: a.name, kind: kindOf(a.name), maps: [], connections: [], pokecenter: false, shops: [], obstacles: [], items: [], npcs: [], trainers: [], events: [],
      };
      if (/static|gift|trade/i.test(pd.methods[method])) staticLocs.add(a.loc);
    }
  const file: AtlasFile = {
    version: 1,
    game: g.id,
    name: g.name,
    generation: g.generation,
    source: { repo: 'PokeAPI + PKHeX encounter tables (via the Pokédex data)', commit: '' },
    locations,
    trainers: {},
    items: {},
    unplaced: [],
    badges: [],
    unverified: {},
  };
  const gaps = `# Pokénav data gaps — ${g.name}

Generated by \`npm run atlas\` (scripts/build-atlas.ts); do not edit. Source: the Pokédex data (PokeAPI + PKHeX encounter tables).

This game has **encounters only**: no decompilation exists to read, and none of the pinned sources lists its maps, items, NPCs, shops or trainer teams (see docs/atlas-sources.md).

| What | Found | Notes |
|---|---|---|
| Locations with encounters | ${Object.keys(locations).length} | place kind (route, city, cave…) is guessed from the name |
| Encounter rows (wild, static, gift, trade) | ${rows} | ${staticLocs.size} locations include static / gift / trade encounters |
| Map, items, NPCs, shops, gyms, trainers | 0 | not available |
`;
  return { file, gaps };
}
