import { expect, test } from '@playwright/test';
import { SAMPLE_TEAM, expectNoA11yViolations, goTo, importTeam, openApp } from './helpers';

/**
 * Meta → Teams. The tournament data is generated by the daily job (Limitless), so the list may be
 * empty in a fresh checkout: the empty state is checked then, and the whole flow when there are teams.
 */
test('Meta Teams tab: browse, filter, open a team, import it, compare, plan, practise', async ({ page }) => {
  await openApp(page);
  await importTeam(page, SAMPLE_TEAM); // a saved team of mine to compare and plan with
  await goTo(page, 'Meta');
  await page.getByRole('tab', { name: 'Teams' }).click();
  const list = page.getByRole('list', { name: 'Tournament teams' });
  await expect(list.or(page.getByText(/No tournament teams for this regulation yet/))).toBeVisible({ timeout: 15_000 });
  if (!(await list.isVisible())) return;

  await expect(page.getByRole('link', { name: /Limitless/ }).first()).toBeVisible();
  const total = await list.getByRole('listitem').count();
  expect(total).toBeGreaterThan(0);
  await page.getByRole('combobox', { name: 'Sort by' }).selectOption('placing');
  await page.getByRole('combobox', { name: 'Mega Evolution' }).selectOption('yes');
  await expect(page.getByRole('status').filter({ hasText: /\d+ teams?/ })).toBeVisible();
  await page.getByRole('combobox', { name: 'Mega Evolution' }).selectOption('');

  await list.getByRole('listitem').first().getByRole('button').click();
  const dialog = page.getByRole('dialog');
  await expect(dialog.getByRole('link', { name: /Limitless/ })).toBeVisible();
  await expect(dialog.getByText(/spread estimated/i).first()).toBeVisible();
  await expectNoA11yViolations(page);

  await dialog.getByRole('button', { name: 'Compare with mine' }).click();
  await expect(dialog.getByRole('combobox', { name: 'My team' })).toBeVisible();
  await dialog.getByRole('button', { name: 'Plan vs this team' }).click();
  await expect(dialog.getByRole('heading', { name: 'Plan vs this team' })).toBeVisible({ timeout: 20_000 });

  await dialog.getByRole('button', { name: 'Import as a team' }).click();
  await expect(dialog.getByRole('button', { name: 'Already imported' })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Practice in Game day' }).click();
  await expect(page).toHaveURL(/#gameday$/);
});
